'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSBridge
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BridgeServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVAResponseModel)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(UserModel)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRITokenModel))>  _
    Partial Public Class BridgeService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendVAInstallmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertPaymentLogOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetBRIVA4TISNetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateBRIVA4TISNetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteBRIVA4TISNetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateBRIVA4TISNetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateTokenAPIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateTokenBRIWTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CollectionPortalDashboard.My.MySettings.Default.VirtualAccount_BrigdeService_BridgeService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event SendVAInstallmentCompleted As SendVAInstallmentCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertPaymentLogCompleted As InsertPaymentLogCompletedEventHandler
        
        '''<remarks/>
        Public Event GetBRIVA4TISNetCompleted As GetBRIVA4TISNetCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateBRIVA4TISNetCompleted As CreateBRIVA4TISNetCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteBRIVA4TISNetCompleted As DeleteBRIVA4TISNetCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateBRIVA4TISNetCompleted As UpdateBRIVA4TISNetCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateTokenAPICompleted As CreateTokenAPICompletedEventHandler
        
        '''<remarks/>
        Public Event CreateTokenBRIWTCompleted As CreateTokenBRIWTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendVAInstallment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendVAInstallment(ByVal transDate As Date) As OutputModel
            Dim results() As Object = Me.Invoke("SendVAInstallment", New Object() {transDate})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendVAInstallmentAsync(ByVal transDate As Date)
            Me.SendVAInstallmentAsync(transDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendVAInstallmentAsync(ByVal transDate As Date, ByVal userState As Object)
            If (Me.SendVAInstallmentOperationCompleted Is Nothing) Then
                Me.SendVAInstallmentOperationCompleted = AddressOf Me.OnSendVAInstallmentOperationCompleted
            End If
            Me.InvokeAsync("SendVAInstallment", New Object() {transDate}, Me.SendVAInstallmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendVAInstallmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendVAInstallmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendVAInstallmentCompleted(Me, New SendVAInstallmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertPaymentLog", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertPaymentLog(ByVal transDate As Date) As OutputModel
            Dim results() As Object = Me.Invoke("InsertPaymentLog", New Object() {transDate})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertPaymentLogAsync(ByVal transDate As Date)
            Me.InsertPaymentLogAsync(transDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertPaymentLogAsync(ByVal transDate As Date, ByVal userState As Object)
            If (Me.InsertPaymentLogOperationCompleted Is Nothing) Then
                Me.InsertPaymentLogOperationCompleted = AddressOf Me.OnInsertPaymentLogOperationCompleted
            End If
            Me.InvokeAsync("InsertPaymentLog", New Object() {transDate}, Me.InsertPaymentLogOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertPaymentLogOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertPaymentLogCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertPaymentLogCompleted(Me, New InsertPaymentLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBRIVA4TISNet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBRIVA4TISNet(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel) As OutputModel
            Dim results() As Object = Me.Invoke("GetBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel)
            Me.GetBRIVA4TISNetAsync(objInputModel, objBRIVAModel, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal userState As Object)
            If (Me.GetBRIVA4TISNetOperationCompleted Is Nothing) Then
                Me.GetBRIVA4TISNetOperationCompleted = AddressOf Me.OnGetBRIVA4TISNetOperationCompleted
            End If
            Me.InvokeAsync("GetBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel}, Me.GetBRIVA4TISNetOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetBRIVA4TISNetOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetBRIVA4TISNetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetBRIVA4TISNetCompleted(Me, New GetBRIVA4TISNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBRIVA4TISNet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateBRIVA4TISNet(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean) As OutputModel
            Dim results() As Object = Me.Invoke("CreateBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean)
            Me.CreateBRIVA4TISNetAsync(objInputModel, objBRIVAModel, LiveEnvironment, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean, ByVal userState As Object)
            If (Me.CreateBRIVA4TISNetOperationCompleted Is Nothing) Then
                Me.CreateBRIVA4TISNetOperationCompleted = AddressOf Me.OnCreateBRIVA4TISNetOperationCompleted
            End If
            Me.InvokeAsync("CreateBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment}, Me.CreateBRIVA4TISNetOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateBRIVA4TISNetOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateBRIVA4TISNetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateBRIVA4TISNetCompleted(Me, New CreateBRIVA4TISNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteBRIVA4TISNet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteBRIVA4TISNet(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean) As OutputModel
            Dim results() As Object = Me.Invoke("DeleteBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean)
            Me.DeleteBRIVA4TISNetAsync(objInputModel, objBRIVAModel, LiveEnvironment, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean, ByVal userState As Object)
            If (Me.DeleteBRIVA4TISNetOperationCompleted Is Nothing) Then
                Me.DeleteBRIVA4TISNetOperationCompleted = AddressOf Me.OnDeleteBRIVA4TISNetOperationCompleted
            End If
            Me.InvokeAsync("DeleteBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment}, Me.DeleteBRIVA4TISNetOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteBRIVA4TISNetOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteBRIVA4TISNetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteBRIVA4TISNetCompleted(Me, New DeleteBRIVA4TISNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBRIVA4TISNet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateBRIVA4TISNet(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean) As OutputModel
            Dim results() As Object = Me.Invoke("UpdateBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean)
            Me.UpdateBRIVA4TISNetAsync(objInputModel, objBRIVAModel, LiveEnvironment, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateBRIVA4TISNetAsync(ByVal objInputModel As InputModel, ByVal objBRIVAModel As BRIVAModel, ByVal LiveEnvironment As Boolean, ByVal userState As Object)
            If (Me.UpdateBRIVA4TISNetOperationCompleted Is Nothing) Then
                Me.UpdateBRIVA4TISNetOperationCompleted = AddressOf Me.OnUpdateBRIVA4TISNetOperationCompleted
            End If
            Me.InvokeAsync("UpdateBRIVA4TISNet", New Object() {objInputModel, objBRIVAModel, LiveEnvironment}, Me.UpdateBRIVA4TISNetOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateBRIVA4TISNetOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateBRIVA4TISNetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateBRIVA4TISNetCompleted(Me, New UpdateBRIVA4TISNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTokenAPI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateTokenAPI(ByVal objInputModel As InputModel) As OutputModel
            Dim results() As Object = Me.Invoke("CreateTokenAPI", New Object() {objInputModel})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateTokenAPIAsync(ByVal objInputModel As InputModel)
            Me.CreateTokenAPIAsync(objInputModel, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateTokenAPIAsync(ByVal objInputModel As InputModel, ByVal userState As Object)
            If (Me.CreateTokenAPIOperationCompleted Is Nothing) Then
                Me.CreateTokenAPIOperationCompleted = AddressOf Me.OnCreateTokenAPIOperationCompleted
            End If
            Me.InvokeAsync("CreateTokenAPI", New Object() {objInputModel}, Me.CreateTokenAPIOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateTokenAPIOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateTokenAPICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateTokenAPICompleted(Me, New CreateTokenAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTokenBRIWT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateTokenBRIWT() As String
            Dim results() As Object = Me.Invoke("CreateTokenBRIWT", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateTokenBRIWTAsync()
            Me.CreateTokenBRIWTAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateTokenBRIWTAsync(ByVal userState As Object)
            If (Me.CreateTokenBRIWTOperationCompleted Is Nothing) Then
                Me.CreateTokenBRIWTOperationCompleted = AddressOf Me.OnCreateTokenBRIWTOperationCompleted
            End If
            Me.InvokeAsync("CreateTokenBRIWT", New Object(-1) {}, Me.CreateTokenBRIWTOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateTokenBRIWTOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateTokenBRIWTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateTokenBRIWTCompleted(Me, New CreateTokenBRIWTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OutputModel
        
        Private errorCodeField As String
        
        Private errorDescriptionField As String
        
        Private resultField As Object
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Result() As Object
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BrivaPaymentModel)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRIVAModel
        
        Private statusBayarField As String
        
        Private lastUpdateField As System.Nullable(Of Date)
        
        Private expiredDateField As Date
        
        Private brivaNoField As String
        
        Private custCodeField As String
        
        Private namaField As String
        
        Private amountField As Double
        
        Private keteranganField As String
        
        '''<remarks/>
        Public Property statusBayar() As String
            Get
                Return Me.statusBayarField
            End Get
            Set
                Me.statusBayarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lastUpdate() As System.Nullable(Of Date)
            Get
                Return Me.lastUpdateField
            End Get
            Set
                Me.lastUpdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property expiredDate() As Date
            Get
                Return Me.expiredDateField
            End Get
            Set
                Me.expiredDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property brivaNo() As String
            Get
                Return Me.brivaNoField
            End Get
            Set
                Me.brivaNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property custCode() As String
            Get
                Return Me.custCodeField
            End Get
            Set
                Me.custCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nama() As String
            Get
                Return Me.namaField
            End Get
            Set
                Me.namaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property keterangan() As String
            Get
                Return Me.keteranganField
            End Get
            Set
                Me.keteranganField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BrivaPaymentModel
        Inherits BRIVAModel
        
        Private paymentDateField As Date
        
        Private telleridField As String
        
        Private no_rekField As String
        
        '''<remarks/>
        Public Property paymentDate() As Date
            Get
                Return Me.paymentDateField
            End Get
            Set
                Me.paymentDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tellerid() As String
            Get
                Return Me.telleridField
            End Get
            Set
                Me.telleridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property no_rek() As String
            Get
                Return Me.no_rekField
            End Get
            Set
                Me.no_rekField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRIVAResponseModel
        
        Private statusField As Boolean
        
        Private responseDescriptionField As String
        
        Private responseCodeField As String
        
        Private errDescField As String
        
        Private error_descriptionField As String
        
        Private dataField As Object
        
        '''<remarks/>
        Public Property status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseDescription() As String
            Get
                Return Me.responseDescriptionField
            End Get
            Set
                Me.responseDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errDesc() As String
            Get
                Return Me.errDescField
            End Get
            Set
                Me.errDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property error_description() As String
            Get
                Return Me.error_descriptionField
            End Get
            Set
                Me.error_descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property data() As Object
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InputModel
        
        Private tokenField As String
        
        Private secretKeyField As String
        
        Private remarksField As String
        
        Private appIDField As String
        
        Private dataField As Object
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecretKey() As String
            Get
                Return Me.secretKeyField
            End Get
            Set
                Me.secretKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Remarks() As String
            Get
                Return Me.remarksField
            End Get
            Set
                Me.remarksField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AppID() As String
            Get
                Return Me.appIDField
            End Get
            Set
                Me.appIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As Object
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UserModel
        
        Private photoLinkField As String
        
        Private employeeNIPField As String
        
        Private employeeNameField As String
        
        Private employeeEmailField As String
        
        Private userIDCodeField As String
        
        Private prodCtrField As String
        
        Private titleField As String
        
        Private departmentField As String
        
        Private groupField As String
        
        Private tokenField As String
        
        '''<remarks/>
        Public Property PhotoLink() As String
            Get
                Return Me.photoLinkField
            End Get
            Set
                Me.photoLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeNIP() As String
            Get
                Return Me.employeeNIPField
            End Get
            Set
                Me.employeeNIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeName() As String
            Get
                Return Me.employeeNameField
            End Get
            Set
                Me.employeeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeEmail() As String
            Get
                Return Me.employeeEmailField
            End Get
            Set
                Me.employeeEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserIDCode() As String
            Get
                Return Me.userIDCodeField
            End Get
            Set
                Me.userIDCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProdCtr() As String
            Get
                Return Me.prodCtrField
            End Get
            Set
                Me.prodCtrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Group() As String
            Get
                Return Me.groupField
            End Get
            Set
                Me.groupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRITokenModel
        
        Private access_tokenField As String
        
        Private expires_inField As Integer
        
        Private token_typeField As String
        
        Private scopeField As String
        
        Private refresh_tokenField As String
        
        Private create_dateField As Date
        
        Private expired_timeField As Date
        
        '''<remarks/>
        Public Property access_token() As String
            Get
                Return Me.access_tokenField
            End Get
            Set
                Me.access_tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property expires_in() As Integer
            Get
                Return Me.expires_inField
            End Get
            Set
                Me.expires_inField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property token_type() As String
            Get
                Return Me.token_typeField
            End Get
            Set
                Me.token_typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property scope() As String
            Get
                Return Me.scopeField
            End Get
            Set
                Me.scopeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property refresh_token() As String
            Get
                Return Me.refresh_tokenField
            End Get
            Set
                Me.refresh_tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property create_date() As Date
            Get
                Return Me.create_dateField
            End Get
            Set
                Me.create_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property expired_time() As Date
            Get
                Return Me.expired_timeField
            End Get
            Set
                Me.expired_timeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendVAInstallmentCompletedEventHandler(ByVal sender As Object, ByVal e As SendVAInstallmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendVAInstallmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InsertPaymentLogCompletedEventHandler(ByVal sender As Object, ByVal e As InsertPaymentLogCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertPaymentLogCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetBRIVA4TISNetCompletedEventHandler(ByVal sender As Object, ByVal e As GetBRIVA4TISNetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetBRIVA4TISNetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateBRIVA4TISNetCompletedEventHandler(ByVal sender As Object, ByVal e As CreateBRIVA4TISNetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateBRIVA4TISNetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DeleteBRIVA4TISNetCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteBRIVA4TISNetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteBRIVA4TISNetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateBRIVA4TISNetCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateBRIVA4TISNetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateBRIVA4TISNetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateTokenAPICompletedEventHandler(ByVal sender As Object, ByVal e As CreateTokenAPICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateTokenAPICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateTokenBRIWTCompletedEventHandler(ByVal sender As Object, ByVal e As CreateTokenBRIWTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateTokenBRIWTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
