'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSFinance
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FinanceServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Employee)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StructuralObject)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(RelatedEnd)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVAModel)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVABulkDetil()))>  _
    Partial Public Class FinanceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPhotoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TPIPusatLogonOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListOfUpdateAmountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateAmountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertBRIVALogOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CollectionPortalDashboard.My.MySettings.Default.VirtualAccount_WSFinance_FinanceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPhotoCompleted As GetPhotoCompletedEventHandler
        
        '''<remarks/>
        Public Event TPIPusatLogonCompleted As TPIPusatLogonCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDataCompleted As GetDataCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListOfUpdateAmountCompleted As GetListOfUpdateAmountCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateAmountCompleted As UpdateAmountCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertBRIVALogCompleted As InsertBRIVALogCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPhoto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPhoto(ByVal UserName As String, ByVal Password As String) As OutputModel
            Dim results() As Object = Me.Invoke("GetPhoto", New Object() {UserName, Password})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPhotoAsync(ByVal UserName As String, ByVal Password As String)
            Me.GetPhotoAsync(UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPhotoAsync(ByVal UserName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.GetPhotoOperationCompleted Is Nothing) Then
                Me.GetPhotoOperationCompleted = AddressOf Me.OnGetPhotoOperationCompleted
            End If
            Me.InvokeAsync("GetPhoto", New Object() {UserName, Password}, Me.GetPhotoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPhotoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPhotoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPhotoCompleted(Me, New GetPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TPIPusatLogon", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TPIPusatLogon(ByVal UserName As String, ByVal Password As String) As OutputModel
            Dim results() As Object = Me.Invoke("TPIPusatLogon", New Object() {UserName, Password})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TPIPusatLogonAsync(ByVal UserName As String, ByVal Password As String)
            Me.TPIPusatLogonAsync(UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TPIPusatLogonAsync(ByVal UserName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.TPIPusatLogonOperationCompleted Is Nothing) Then
                Me.TPIPusatLogonOperationCompleted = AddressOf Me.OnTPIPusatLogonOperationCompleted
            End If
            Me.InvokeAsync("TPIPusatLogon", New Object() {UserName, Password}, Me.TPIPusatLogonOperationCompleted, userState)
        End Sub
        
        Private Sub OnTPIPusatLogonOperationCompleted(ByVal arg As Object)
            If (Not (Me.TPIPusatLogonCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TPIPusatLogonCompleted(Me, New TPIPusatLogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetData(ByVal brivaNo As String) As OutputModel
            Dim results() As Object = Me.Invoke("GetData", New Object() {brivaNo})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDataAsync(ByVal brivaNo As String)
            Me.GetDataAsync(brivaNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDataAsync(ByVal brivaNo As String, ByVal userState As Object)
            If (Me.GetDataOperationCompleted Is Nothing) Then
                Me.GetDataOperationCompleted = AddressOf Me.OnGetDataOperationCompleted
            End If
            Me.InvokeAsync("GetData", New Object() {brivaNo}, Me.GetDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDataCompleted(Me, New GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListOfUpdateAmount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListOfUpdateAmount(ByVal SUID As System.Guid) As OutputModel
            Dim results() As Object = Me.Invoke("GetListOfUpdateAmount", New Object() {SUID})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListOfUpdateAmountAsync(ByVal SUID As System.Guid)
            Me.GetListOfUpdateAmountAsync(SUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListOfUpdateAmountAsync(ByVal SUID As System.Guid, ByVal userState As Object)
            If (Me.GetListOfUpdateAmountOperationCompleted Is Nothing) Then
                Me.GetListOfUpdateAmountOperationCompleted = AddressOf Me.OnGetListOfUpdateAmountOperationCompleted
            End If
            Me.InvokeAsync("GetListOfUpdateAmount", New Object() {SUID}, Me.GetListOfUpdateAmountOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListOfUpdateAmountOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListOfUpdateAmountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListOfUpdateAmountCompleted(Me, New GetListOfUpdateAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAmount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateAmount(ByVal ListOfSeq As String, ByVal SUID As System.Guid, ByVal userid As String) As OutputModel
            Dim results() As Object = Me.Invoke("UpdateAmount", New Object() {ListOfSeq, SUID, userid})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateAmountAsync(ByVal ListOfSeq As String, ByVal SUID As System.Guid, ByVal userid As String)
            Me.UpdateAmountAsync(ListOfSeq, SUID, userid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAmountAsync(ByVal ListOfSeq As String, ByVal SUID As System.Guid, ByVal userid As String, ByVal userState As Object)
            If (Me.UpdateAmountOperationCompleted Is Nothing) Then
                Me.UpdateAmountOperationCompleted = AddressOf Me.OnUpdateAmountOperationCompleted
            End If
            Me.InvokeAsync("UpdateAmount", New Object() {ListOfSeq, SUID, userid}, Me.UpdateAmountOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateAmountOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateAmountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateAmountCompleted(Me, New UpdateAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBRIVALog", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertBRIVALog(ByVal SUID As System.Guid) As OutputModel
            Dim results() As Object = Me.Invoke("InsertBRIVALog", New Object() {SUID})
            Return CType(results(0),OutputModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertBRIVALogAsync(ByVal SUID As System.Guid)
            Me.InsertBRIVALogAsync(SUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertBRIVALogAsync(ByVal SUID As System.Guid, ByVal userState As Object)
            If (Me.InsertBRIVALogOperationCompleted Is Nothing) Then
                Me.InsertBRIVALogOperationCompleted = AddressOf Me.OnInsertBRIVALogOperationCompleted
            End If
            Me.InvokeAsync("InsertBRIVALog", New Object() {SUID}, Me.InsertBRIVALogOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertBRIVALogOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertBRIVALogCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertBRIVALogCompleted(Me, New InsertBRIVALogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OutputModel
        
        Private errorCodeField As String
        
        Private errorDescriptionField As String
        
        Private resultField As Object
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Result() As Object
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Employee
        
        Private employeeNIPField As String
        
        Private employeeNameField As String
        
        Private employeeEmailField As String
        
        Private userIDCodeField As String
        
        Private prodCtrField As String
        
        Private titleField As String
        
        Private departmentField As String
        
        Private groupField As String
        
        '''<remarks/>
        Public Property EmployeeNIP() As String
            Get
                Return Me.employeeNIPField
            End Get
            Set
                Me.employeeNIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeName() As String
            Get
                Return Me.employeeNameField
            End Get
            Set
                Me.employeeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeEmail() As String
            Get
                Return Me.employeeEmailField
            End Get
            Set
                Me.employeeEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserIDCode() As String
            Get
                Return Me.userIDCodeField
            End Get
            Set
                Me.userIDCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProdCtr() As String
            Get
                Return Me.prodCtrField
            End Get
            Set
                Me.prodCtrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Group() As String
            Get
                Return Me.groupField
            End Get
            Set
                Me.groupField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityObject)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVABulk)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVABulkDetil)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class StructuralObject
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVABulk)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BRIVABulkDetil)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class EntityObject
        Inherits StructuralObject
        
        Private entityKeyField As EntityKey
        
        '''<remarks/>
        Public Property EntityKey() As EntityKey
            Get
                Return Me.entityKeyField
            End Get
            Set
                Me.entityKeyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EntityKey
        
        Private entitySetNameField As String
        
        Private entityContainerNameField As String
        
        Private entityKeyValuesField() As EntityKeyMember
        
        '''<remarks/>
        Public Property EntitySetName() As String
            Get
                Return Me.entitySetNameField
            End Get
            Set
                Me.entitySetNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntityContainerName() As String
            Get
                Return Me.entityContainerNameField
            End Get
            Set
                Me.entityContainerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntityKeyValues() As EntityKeyMember()
            Get
                Return Me.entityKeyValuesField
            End Get
            Set
                Me.entityKeyValuesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EntityKeyMember
        
        Private keyField As String
        
        Private valueField As Object
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRIVABulk
        Inherits EntityObject
        
        Private suidField As System.Guid
        
        Private brivanoField As String
        
        Private custCodeField As String
        
        Private payeeIDField As String
        
        Private custNameField As String
        
        Private tYPEField As String
        
        Private overwriteAddRemoveField As String
        
        Private amountField As Decimal
        
        Private keteranganField As String
        
        Private bRIVADueDateField As Date
        
        Private lastJobScheduleRunSeqField As Integer
        
        Private createDateField As Date
        
        Private isSystemField As Boolean
        
        '''<remarks/>
        Public Property Suid() As System.Guid
            Get
                Return Me.suidField
            End Get
            Set
                Me.suidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Brivano() As String
            Get
                Return Me.brivanoField
            End Get
            Set
                Me.brivanoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustCode() As String
            Get
                Return Me.custCodeField
            End Get
            Set
                Me.custCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PayeeID() As String
            Get
                Return Me.payeeIDField
            End Get
            Set
                Me.payeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustName() As String
            Get
                Return Me.custNameField
            End Get
            Set
                Me.custNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TYPE() As String
            Get
                Return Me.tYPEField
            End Get
            Set
                Me.tYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OverwriteAddRemove() As String
            Get
                Return Me.overwriteAddRemoveField
            End Get
            Set
                Me.overwriteAddRemoveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Keterangan() As String
            Get
                Return Me.keteranganField
            End Get
            Set
                Me.keteranganField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BRIVADueDate() As Date
            Get
                Return Me.bRIVADueDateField
            End Get
            Set
                Me.bRIVADueDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastJobScheduleRunSeq() As Integer
            Get
                Return Me.lastJobScheduleRunSeqField
            End Get
            Set
                Me.lastJobScheduleRunSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreateDate() As Date
            Get
                Return Me.createDateField
            End Get
            Set
                Me.createDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsSystem() As Boolean
            Get
                Return Me.isSystemField
            End Get
            Set
                Me.isSystemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRIVABulkDetil
        Inherits EntityObject
        
        Private suidField As System.Guid
        
        Private seqNbrField As Integer
        
        Private checkedField As Boolean
        
        Private policyNumberField As String
        
        Private endtTypeField As String
        
        Private cancelReplaceFlagField As String
        
        Private docNbrField As String
        
        Private docTypeField As String
        
        Private installmentSeqField As Integer
        
        Private amountField As Decimal
        
        Private bRIVABulkReferenceField As EntityReferenceOfBRIVABulk
        
        '''<remarks/>
        Public Property Suid() As System.Guid
            Get
                Return Me.suidField
            End Get
            Set
                Me.suidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SeqNbr() As Integer
            Get
                Return Me.seqNbrField
            End Get
            Set
                Me.seqNbrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Checked() As Boolean
            Get
                Return Me.checkedField
            End Get
            Set
                Me.checkedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PolicyNumber() As String
            Get
                Return Me.policyNumberField
            End Get
            Set
                Me.policyNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndtType() As String
            Get
                Return Me.endtTypeField
            End Get
            Set
                Me.endtTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CancelReplaceFlag() As String
            Get
                Return Me.cancelReplaceFlagField
            End Get
            Set
                Me.cancelReplaceFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocNbr() As String
            Get
                Return Me.docNbrField
            End Get
            Set
                Me.docNbrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocType() As String
            Get
                Return Me.docTypeField
            End Get
            Set
                Me.docTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InstallmentSeq() As Integer
            Get
                Return Me.installmentSeqField
            End Get
            Set
                Me.installmentSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BRIVABulkReference() As EntityReferenceOfBRIVABulk
            Get
                Return Me.bRIVABulkReferenceField
            End Get
            Set
                Me.bRIVABulkReferenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EntityReferenceOfBRIVABulk
        Inherits EntityReference
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityReferenceOfBRIVABulk)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class EntityReference
        Inherits RelatedEnd
        
        Private entityKeyField As EntityKey
        
        '''<remarks/>
        Public Property EntityKey() As EntityKey
            Get
                Return Me.entityKeyField
            End Get
            Set
                Me.entityKeyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityReference)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityReferenceOfBRIVABulk)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class RelatedEnd
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BrivaPaymentModel)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BRIVAModel
        
        Private statusBayarField As String
        
        Private lastUpdateField As System.Nullable(Of Date)
        
        Private expiredDateField As Date
        
        Private brivaNoField As String
        
        Private custCodeField As String
        
        Private namaField As String
        
        Private amountField As Double
        
        Private keteranganField As String
        
        '''<remarks/>
        Public Property statusBayar() As String
            Get
                Return Me.statusBayarField
            End Get
            Set
                Me.statusBayarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lastUpdate() As System.Nullable(Of Date)
            Get
                Return Me.lastUpdateField
            End Get
            Set
                Me.lastUpdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property expiredDate() As Date
            Get
                Return Me.expiredDateField
            End Get
            Set
                Me.expiredDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property brivaNo() As String
            Get
                Return Me.brivaNoField
            End Get
            Set
                Me.brivaNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property custCode() As String
            Get
                Return Me.custCodeField
            End Get
            Set
                Me.custCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nama() As String
            Get
                Return Me.namaField
            End Get
            Set
                Me.namaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property keterangan() As String
            Get
                Return Me.keteranganField
            End Get
            Set
                Me.keteranganField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BrivaPaymentModel
        Inherits BRIVAModel
        
        Private paymentDateField As Date
        
        Private telleridField As String
        
        Private no_rekField As String
        
        '''<remarks/>
        Public Property paymentDate() As Date
            Get
                Return Me.paymentDateField
            End Get
            Set
                Me.paymentDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tellerid() As String
            Get
                Return Me.telleridField
            End Get
            Set
                Me.telleridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property no_rek() As String
            Get
                Return Me.no_rekField
            End Get
            Set
                Me.no_rekField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetPhotoCompletedEventHandler(ByVal sender As Object, ByVal e As GetPhotoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPhotoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub TPIPusatLogonCompletedEventHandler(ByVal sender As Object, ByVal e As TPIPusatLogonCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TPIPusatLogonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetDataCompletedEventHandler(ByVal sender As Object, ByVal e As GetDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetListOfUpdateAmountCompletedEventHandler(ByVal sender As Object, ByVal e As GetListOfUpdateAmountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListOfUpdateAmountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateAmountCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateAmountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateAmountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InsertBRIVALogCompletedEventHandler(ByVal sender As Object, ByVal e As InsertBRIVALogCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertBRIVALogCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputModel)
            End Get
        End Property
    End Class
End Namespace
