'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewSite

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''scriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblUname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RoleAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoleAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuPayment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuPaymentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuPaymentList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuSettlementMonitoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuSettlementMonitoring As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuMandiri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuMandiri As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuGenerateVirtualAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuGenerateVirtualAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuBRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuBRI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuResendBRIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuResendBRIVA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuReportMandiri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuReportMandiri As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuReportMandiriVAClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuReportMandiriVAClient As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuUserManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuUserManagement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAddPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAddPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAddAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAddAccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAddUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAddUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuChangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuChangePwd As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
